import {
  FaPlay,
  FaPause,
  FaStickyNote,
  FaUserAlt,
  FaMedal,
  FaHeadphones,
  FaCrown,
  FaLock,
  FaFan,
} from "react-icons/fa";
import {
  BsFillSkipBackwardFill,
  BsSkipForwardFill,
  BsCloudRainFill,
  BsFillTreeFill,
  BsPhoneFill,
  BsFillCalendarDateFill,
  BsInfoCircle,
  BsCaretUpFill,
  BsCaretDownFill,
  BsFillInfoCircleFill,
  BsSpotify,
  BsSoundwave,
  BsLightningCharge,
  BsArrowRepeat,
  BsCheck2,
  BsKeyboardFill,
  BsAirplaneFill,
  BsTrainFrontFill,
} from "react-icons/bs";
import {
  IoVolumeMedium,
  IoVolumeMute,
  IoVolumeOff,
  IoCloseOutline,
  IoThunderstorm,
  IoBookSharp,
  IoCloudyNight,
  IoCheckmarkCircle,
  IoSnowSharp,
  IoAlarm,
  IoLogoYoutube,
  IoCheckmarkCircleSharp,
} from "react-icons/io5";
import {
  RiSoundModuleFill,
  RiFullscreenFill,
  RiFullscreenExitLine,
  RiPlayListFill,
} from "react-icons/ri";
import { HiChatBubbleLeftRight, HiBuildingOffice2, HiClipboardDocumentList } from "react-icons/hi2";
import { HiTemplate } from "react-icons/hi";
import { ImTwitter, ImCalculator } from "react-icons/im";
import { WiNightAltStormShowers } from "react-icons/wi";
import { CgEditNoise, CgArrowsExpandDownRight, CgArrowsExpandUpLeft } from "react-icons/cg";
import { GiTacos, GiBigWave, GiSubmarine } from "react-icons/gi";
import {
  MdLandscape,
  MdDelete,
  MdModeEdit,
  MdOutlineDone,
  MdOutlineMenu,
  MdSettings,
  MdTimer,
  MdEmail,
  MdWaterDrop,
  MdLibraryMusic,
  MdOutlineDisabledByDefault,
  MdError,
  MdMoreHoriz,
  MdOutlineCheckBoxOutlineBlank,
  MdCheckBox,
} from "react-icons/md";
import {
  AiFillTool,
  AiOutlineGoogle,
  AiFillInstagram,
  AiFillClockCircle,
  AiFillFire,
  AiFillThunderbolt,
} from "react-icons/ai";
import { FiPlus } from "react-icons/fi";
import { FaCommentDots, FaHandsHelping } from "react-icons/fa";
import {
  RxCaretLeft,
  RxCaretRight,
  RxReset,
  RxTimer,
  RxCaretDown,
  RxCaretUp,
  RxDragHandleDots2,
} from "react-icons/rx";
import { PiMoonFill, PiSunHorizonFill, PiWavesDuotone } from "react-icons/pi";
import { VscDebugRestart } from "react-icons/vsc";
import { LuGalleryVertical, LuGalleryHorizontal } from "react-icons/lu";
import { BiSolidHide, BiSolidShow } from "react-icons/bi";

export {
  FaPause,
  FaPlay,
  BsFillSkipBackwardFill,
  BsSkipForwardFill,
  IoVolumeMedium,
  IoVolumeMute,
  RiSoundModuleFill,
  IoVolumeOff,
  BsCloudRainFill,
  BsFillTreeFill,
  IoCloseOutline,
  HiChatBubbleLeftRight,
  HiBuildingOffice2,
  ImTwitter,
  RiFullscreenFill,
  RiFullscreenExitLine,
  WiNightAltStormShowers,
  FaFan,
  CgEditNoise,
  IoThunderstorm,
  IoCheckmarkCircle,
  PiWavesDuotone,
  GiTacos,
  MdLandscape,
  BsPhoneFill,
  AiFillTool,
  AiOutlineGoogle,
  BsFillCalendarDateFill,
  FaStickyNote,
  HiClipboardDocumentList,
  BsInfoCircle,
  GiBigWave,
  FiPlus,
  MdDelete,
  MdModeEdit,
  MdOutlineDone,
  BsCaretUpFill,
  BsCaretDownFill,
  MdOutlineMenu,
  MdSettings,
  FaCommentDots,
  BsFillInfoCircleFill,
  MdTimer,
  MdOutlineDisabledByDefault,
  RxCaretLeft,
  RxCaretRight,
  RxCaretDown,
  RxCaretUp,
  RxReset,
  FaHandsHelping,
  BsSpotify,
  FaUserAlt,
  FaMedal,
  AiFillInstagram,
  MdEmail,
  MdWaterDrop,
  PiMoonFill,
  FaHeadphones,
  FaCrown,
  IoBookSharp,
  MdLibraryMusic,
  MdError,
  RiPlayListFill,
  BsSoundwave,
  HiTemplate,
  VscDebugRestart,
  RxTimer,
  BsLightningCharge,
  BsArrowRepeat,
  BsCheck2,
  BsKeyboardFill,
  BsAirplaneFill,
  AiFillClockCircle,
  AiFillFire,
  PiSunHorizonFill,
  IoSnowSharp,
  IoCloudyNight,
  BsTrainFrontFill,
  GiSubmarine,
  FaLock,
  AiFillThunderbolt,
  MdMoreHoriz,
  CgArrowsExpandDownRight,
  CgArrowsExpandUpLeft,
  RxDragHandleDots2,
  LuGalleryVertical,
  LuGalleryHorizontal,
  ImCalculator,
  IoAlarm,
  IoLogoYoutube,
  BiSolidHide,
  BiSolidShow,
  MdOutlineCheckBoxOutlineBlank,
  MdCheckBox,
  IoCheckmarkCircleSharp,
};
