import {
  BsCloudRain,
  HiOutlineChatBubbleLeftRight,
  BsTree,
  SlSocialTwitter,
  HiOutlineBuildingOffice2,
  WiNightAltStormShowers,
  LuFan,
  CgEditNoise,
  IoThunderstormOutline,
  LuWaves,
  GiBigWave,
  MdOutlineWaterDrop,
  BsKeyboard,
  AiOutlineClockCircle,
  BsAirplane,
  AiOutlineFire,
  PiSunHorizonLight,
  PiSnowflakeThin,
  IoCloudyNightOutline,
  BsTrainFront,
  TbSubmarine,
} from "@/imports/icons";

export const soundIcons = {
  RAIN: <BsCloudRain />,
  CHATTER: <HiOutlineChatBubbleLeftRight />,
  NATURE: <BsTree />,
  BIRDS_CHIRPING: <SlSocialTwitter />,
  CITY_TRAFFIC: <HiOutlineBuildingOffice2 />,
  STORMY_NIGHT: <WiNightAltStormShowers />,
  FAN: <LuFan />,
  WHITE_NOISE: <LuWaves />,
  THUNDER: <IoThunderstormOutline />,
  AMBIENCE: <CgEditNoise />,
  OCEAN: <GiBigWave />,
  WATER: <MdOutlineWaterDrop />,
  AIRPLANE: <BsAirplane />,
  CLOCK: <AiOutlineClockCircle />,
  FIRE_PLACE: <AiOutlineFire />,
  KEYBOARD: <BsKeyboard />,
  MORNING: <PiSunHorizonLight />,
  SNOW: <PiSnowflakeThin />,
  SUMMER_NIGHT: <IoCloudyNightOutline />,
  TRAIN: <BsTrainFront />,
  UNDERWATER: <TbSubmarine />,
};
