import "./landing-page-global.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Melofi",
  description: "Generated by create next app",
};
export default function HomeLayout({ children }: { children: React.ReactNode }) {
  return <div id="home-layout">{children}</div>;
}
