import type { Metadata } from "next";
import "./globals.css";
import NotificationProvider from "@/providers/notificationProvider/NotificationProvider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import AuthProvider from "@/providers/authProvider/AuthProvider";
import AppContextProvider from "@/contexts/AppContext";

export const metadata: Metadata = {
  title: "Melofi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          display: "flex",
          flexDirection: "column",
          height: "100vh",
        }}
      >
        <GoogleOAuthProvider clientId="922776747697-hbq7p19u2jmjjb1ksf4s0h95mmiu4pht.apps.googleusercontent.com">
          <AuthProvider>
            <NotificationProvider>
              <AppContextProvider>{children}</AppContextProvider>
            </NotificationProvider>
          </AuthProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
