import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/Header";
import SceneBackground from "@/components/sceneBackground/SceneBackground";

export const metadata: Metadata = {
  title: "Melofi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="melofi-app">
        <Header />
        <SceneBackground />
        {children}
      </body>
    </html>
  );
}
