import type { Metadata } from "next";
import "./portal-page-global.css";

export const metadata: Metadata = {
  title: "Melofi",
  description: "Generated by create next app",
};
export default function PortalLayout({ children }: { children: React.ReactNode }) {
  return <div id="portal-layout">{children}</div>;
}
