name: Cypress E2E Tests

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Start Firebase Emulators
        run: firebase emulators:start --only auth,firestore --project test-project --port=9099 --host=0.0.0.0 --ui-port=4000

      - name: Run Cypress tests
        run: npm run test:e2e:headless
