# name: Cypress E2E Tests

# on:
#   pull_request:
#     branches:
#       - develop
#     types:
#       - opened # Trigger when a pull request is opened
#       - synchronize # Trigger when a pull request is updated

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         #Use the latest version of Node.js
#         node-version: [18.x]
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: Set up environment variables
#         env:
#           FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
#           NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
#           NEXT_PUBLIC_IS_CYPRESS: ${{ secrets.NEXT_PUBLIC_IS_CYPRESS }}

#         run: |
#           echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> $GITHUB_ENV
#           echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" >> $GITHUB_ENV
#           echo "NEXT_PUBLIC_IS_CYPRESS: ${{ secrets.NEXT_PUBLIC_IS_CYPRESS }}" >> $GITHUB_ENV

#       - name: Install dependencies
#         run: npm install

#       - name: Start Firebase Emulators
#         run: firebase emulators:start --only auth,firestore --project test-project &

#       - name: Run Cypress tests
#         run: npm run test:e2e:headless
#         env:
#           FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
#           NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
#           NEXT_PUBLIC_IS_CYPRESS: ${{ secrets.NEXT_PUBLIC_IS_CYPRESS }}
#           CI: true
name: Cypress E2E Tests

on:
  pull_request:
    branches:
      - develop
    types:
      - opened # Trigger when a pull request is opened
      - synchronize # Trigger when a pull request is updated

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #Use the latest version of Node.js
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test:e2e:headless:github
        env:
          CI: true
