name: Cypress E2E Tests

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Firebase Authentication
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "${FIREBASE_SERVICE_ACCOUNT}" > firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account.json

      - name: Check if Firebase Emulator Cache Exists
        run: |
          if [ -d "/home/runner/.cache/firebase/emulators" ]; then
            echo "Cache directory exists."
          else
            echo "Cache directory does not exist."
          fi

      # Ensure the Firebase Emulator cache is cleared
      - name: Clear Firebase Emulator Cache
        run: rm -rf /home/runner/.cache/firebase/emulators

      - name: Verify Firebase Emulator Cache is Cleared
        run: |
          if [ -d "/home/runner/.cache/firebase/emulators" ]; then
            echo "Cache directory still exists!"
            exit 1
          else
            echo "Cache directory has been successfully cleared."
          fi

      # Start Firebase emulators with no persistence
      - name: Start Firebase Emulators
        env:
          GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json
        run: |
          firebase emulators:start --only auth,firestore --project test-project | tee emulator-log.txt &
          sleep 10 # Allow time for emulators to start

      - name: Run Cypress tests
        run: npm run test:e2e:headless:github
        env:
          CI: true
          NEXT_PUBLIC_IS_CYPRESS: "true"
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}

      - name: Upload Cypress Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
